### ISSUE TITLE
Move all text from templates to locale file

### ISSUE THREAD

**Issue by matronator** [matronator/GlobalCollapse#1]
Lot of the UI text in the game is hardcoded in the template files (due to my laziness and poor planning ahead) and should be replaced with link to the locale file [here](https://github.com/matronator/GlobalCollapse/blob/master/app/lang/general.en_US.neon).

So for example you'd change this:

> app/modules/Front/templates/Default/default.latte

```latte
...
<ul class="uk-list uk-list-divider uk-margin-remove">
    <li>Level</li>
    <li>Money</li>
    <li>Energy</li>
</ul>
...
```

To this:

> app/modules/Front/templates/Default/default.latte

```latte
...
<ul class="uk-list uk-list-divider uk-margin-remove">
    <li>{_general.stats.level.title}</li>
    <li>{_general.stats.money.title}</li>
    <li>{_general.stats.energy.title}</li>
</ul>
...
```

> app/lang/general.en_US.neon

```neon
...
stats:
    level:
        title: 'Level'
    money:
        title: 'Money'
    energy:
        title: 'Energy'
...
```

If you want to help out with that, please search the locale file (CTRL+F / CMD+F) if there isn't an entry for the same phrase already before creating new entry to prevent duplicates.

No need to create an entry in the `cs_CZ` locale file as well, that can be translated later. Right now, the priority is English.

**Comment by Yarblen** [comment]
Interested in a german version?

**Comment by matronator** [comment]
Sure, that'd be great if you're up to it! :)

**Comment by Yarblen** [comment]
Ok, will you open a new path for german and I will translate the code. Tell me what I have to so.

**Comment by Yarblen** [comment]
Took a copy and working on it.

**Comment by matronator** [comment]
If you need any help with it, just let me know.
