### ISSUE TITLE
[BUG] script(s) is incomplete 

### ISSUE THREAD

**Issue by Janvier123** [matronator/GlobalCollapse#10]
Iam tring to figure out how the "collect" on the buildings module works, i cant seem to find it
Howerver iam missing valuable parts of the game,

- MySQL file is a mess, loads of errors 
- table "drugs_inventory" missing ???
- Collect system is missing or not existing

**PLEASE update the git to the latest working files please**

Thx

**Comment by matronator** [comment]
Hi, thanks for the issue! I've updated the SQL file to the latest dump, it should now have everything needed for it to work. I also added a MySQL workbench schema in the root saved as `globalcollapse.mwb`. Note that if you create your database using the schema, you will still have to insert some data manually for it to work - specifically tables `vendors` (or you can create them manually in the admin), `drugs` and `buildings` and optionally `vendor_offers` though they might be generated from the administration.

I also added the scripts that are run automatically. However they won't run automatically and I don't know how to help you with that. I use my hosting provider's function to run these files periodically, I don't know how to set it up by yourself. The files are in the root saved as `buildings-collect.php` and `drugs-prices.php`. Also there is one function in the administration that is also being run automatically every few hours and that's `actionUpdateOffers` in the `VendorPresenter.php` in the `Admin` module - the hash needed as a parameter is saved in `config.local.neon` (or in the example `config.local.neon.example`) under `parameters`.

**Comment by Janvier123** [comment]
sweet! Thx that helps ALLOT and wil get others started
