### ISSUE TITLE
Global Collapse Darknet

### ISSUE THREAD

**Issue by Yarblen** [matronator/GlobalCollapse#14]
Hello,

I want to ask about the darknet: There are no requests for Meth since a long time, only MDMA? What is this?

Greetz, Yarblen

**Comment by matronator** [comment]
Fixed in 6151105596955799d26dcdef4799d5281b62cea6 . Should be more balanced now. If the vendor runs out of money, he will change his offer and replenish his money so you can sell to him again (if he changed to what you need). So no more having all vendors without cash and no way to reset them.
