### ISSUE TITLE
[BUG]Meth purchased amount isn't visable. 

### ISSUE THREAD

**Issue by techfirstuk** [matronator/GlobalCollapse#3]
https://global-collapse.com/darknet

Darknet value once purchasing Heroin There is no value for the quantity of purchased Heroin of the right hand column.

**Comment by matronator** [comment]
Could you provide some screenshots and more details about your specs (what browser are you on, mobile or desktop, etc...)?

**Comment by techfirstuk** [comment]
![image](https://user-images.githubusercontent.com/64167390/83907211-f061ea00-a75c-11ea-8521-84c2bd6ef142.png)

Right hand side on the table there is no Heroin showing even though i have bought it in a large amount.

**Comment by matronator** [comment]
Thank you, it's much appreciated :) I'm going to look into that as soon as possible, in the meantime, I'd like to ask couple more questions if you don't mind:

1. How much did you try to buy?
2. Does this happen even if you try to buy just 1g?
3. Can I ask what is your in-game name? This so I could find your player inventory in the database to help me find the cause of this bug.

If you don't want to share this information here in public, you can also contact me privately via email at: [info@global-collapse.com](mailto:info@global-collapse.com)

Thanks again for reporting this!

**Comment by techfirstuk** [comment]
I think this was my bad. purchased more and it appeared.
