### ISSUE TITLE
[BUG] https://global-collapse.com:80/buildings?_fid=****

### ISSUE THREAD

**Issue by techfirstuk** [matronator/GlobalCollapse#7]
This site can’t provide a secure connectionglobal-collapse.com sent an invalid response.
Try running Windows Network Diagnostics.
ERR_SSL_PROTOCOL_ERROR

**Comment by uaktags** [comment]
The https doesn't appear to be working on their server, need to force it as http. Probably a reverse-proxy issue.

**Comment by matronator** [comment]
Fixed, sorry it took so long.
